import fs from "node:fs";
import path from "node:path";
import ts from "typescript";

const root = process.cwd();
const srcRoot = path.join(root, "src");
const entry = path.join(srcRoot, "main.ts");
const outFile = path.join(srcRoot, "Worms.js");
const outMap = `${outFile}.map`;

const referencePattern = /^\s*\/\/\/\s*<reference\s+path=["']([^"']+)["']\s*\/>\s*$/im;
const visited = new Set<string>();
const ordered: string[] = [];

function resolveCaseInsensitive(filePath: string): string {
  if (fs.existsSync(filePath)) {
    return filePath;
  }

  const dir = path.dirname(filePath);
  const base = path.basename(filePath).toLowerCase();
  if (!fs.existsSync(dir)) {
    throw new Error(`Cannot resolve directory for ${filePath}`);
  }

  const match = fs.readdirSync(dir).find((entryName) => entryName.toLowerCase() === base);
  if (!match) {
    throw new Error(`Cannot resolve legacy reference ${filePath}`);
  }

  return path.join(dir, match);
}

function collect(filePath: string): void {
  const resolved = resolveCaseInsensitive(filePath);
  const normalized = path.normalize(resolved);
  const visitKey = normalized.toLowerCase();
  if (visited.has(visitKey)) {
    return;
  }
  visited.add(visitKey);

  const source = fs.readFileSync(normalized, "utf8");
  for (const line of source.split(/\r?\n/)) {
    const match = referencePattern.exec(line);
    if (!match) {
      continue;
    }
    const reference = match[1];
    if (reference.endsWith(".d.ts")) {
      continue;
    }
    collect(path.resolve(path.dirname(normalized), reference));
  }

  ordered.push(normalized);
}

function transpile(filePath: string): string {
  const source = fs.readFileSync(filePath, "utf8");
  const result = ts.transpileModule(source, {
    fileName: filePath,
    compilerOptions: {
      target: ts.ScriptTarget.ES5,
      module: ts.ModuleKind.None,
      sourceMap: false,
      removeComments: false,
      isolatedModules: false,
      ignoreDeprecations: "6.0"
    },
    reportDiagnostics: true
  });

  const ignoredCodes = new Set([5047, 5107]);
  const blocking = (result.diagnostics ?? []).filter(
    (diagnostic) => diagnostic.category === ts.DiagnosticCategory.Error && !ignoredCodes.has(diagnostic.code)
  );
  if (blocking.length > 0) {
    const formatted = ts.formatDiagnosticsWithColorAndContext(blocking, {
      getCanonicalFileName: (name) => name,
      getCurrentDirectory: () => root,
      getNewLine: () => "\n"
    });
    throw new Error(formatted);
  }

  return [
    `// ---- ${path.relative(root, filePath)} ----`,
    result.outputText.trimEnd()
  ].join("\n");
}

collect(entry);

const chunks = ordered
  .filter((filePath) => !filePath.endsWith(".d.ts"))
  .map(transpile);

const banner = [
  "/*",
  " * Generated by scripts/build-legacy.ts.",
  " * Do not edit directly; change the TypeScript sources instead.",
  " */"
].join("\n");

fs.writeFileSync(outFile, `${banner}\n${chunks.join("\n\n")}\n`);
fs.writeFileSync(outMap, "");

console.log(`Built ${path.relative(root, outFile)} from ${ordered.length} legacy TypeScript files.`);
